version: '3.5'
services:
  api01: &api
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    image: skarllot/rinha-api:2024Q1
    environment:
      - ASPNETCORE_URLS=http://*:8080
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '100MB'

  api02:
    <<: *api

  lb:
    image: nginx:1.25.4
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api01
      - api02
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '10MB'

  db:
    image: postgres:16.2
    command: 'postgres -c shared_buffers=256MB -c max_connections=1000'
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql:ro
    environment:
      - POSTGRES_PASSWORD=rinha2024q1
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '340MB'
    restart: on-failure
    healthcheck:
      test: [ "CMD", "pg_isready", "--username", "rinha" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

networks:
  default:
    driver: bridge
    name: rinha-marten-2024q1
